services:
    php:
        build:
            context: ./docker/php
        environment:
            - SYMFONY_PARAMS=${SYMFONY_PARAMS:-}
        volumes:
            - ./:/var/www/camper2012.ru
        ports:
            - '9000:9000'
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE: ${MYSQL_DB:-app}
            MYSQL_USER: ${MYSQL_USER:-app}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
        volumes:
            - ./var/mysql:/var/lib/mysql
        ports:
            - "3306:3306"

